// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgtczesvqdsqqvjyylj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z3RjemVzdnFkc3Fxdmp5eWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDAxNjEsImV4cCI6MjA2NjAxNjE2MX0.ZbXuh83J7wfDc0Rbb0owO4Ds-BVXrCcr3wXypDhoOCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);